ui: mocha-qunit
browsers:
    - name: firefox
      version: latest
    - name: chrome
      version: latest
    - name: chrome
      version: latest
    - name: ie
      version: 9..latest
    - name: iphone
      version: latest
